joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  # 发布频率，单位为Hz
  source_list: ['front_left_wheel_joint', 'front_right_wheel_joint', 'back_left_wheel_joint', 'back_right_wheel_joint']
